### PR TITLE
Change order of cells

### PR DESCRIPTION
**Pull request by samwaseda**

### CODE REVIEW

**Comment by jan-janssen** [comment]
I do not understand why this is necessary.

**Comment by samwaseda** [comment]
ok I thought it was obvious from the change.


```python
def create_env(env_key):
    subprocess.check_output(
        ["mamba", "env", "create", "-n", env_key, "-f", env_dict[env_key], "-y"],
        universal_newlines=True,
    ).split("\n")

env_dict = {
    "preprocessing": "source/envs/preprocessing.yaml",
    "processing": "source/envs/processing.yaml",
    "postprocessing": "source/envs/postprocessing.yaml"
}
```

- `env_dict` is used in the function before it's defined and/or
- `env_dict` is not defined in the function

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by jan-janssen** [comment]
I fixed it in https://github.com/pyiron-dev/NFDI4Ing_pyiron_base/commit/05a91c47547904186326039aa8c054cea4a1e6ad as somehow there was a merge conflict with this branch.

**Pull request closed without merging**
